### ISSUE TITLE
Able to turn off HTTP logging?

### ISSUE THREAD

**Issue by imrichardcole** [TheYonkk/influxdb-cpp-2.0#1]
Great client, but I'd like to avoid the logging that's printed to the screen on each write i.e HTTP POST details.

Could this be made optional?

Obviously I could go in and pull out all the printf() statements in the hpp but figure this could be a more general feature.

**Comment by sethcall** [comment]
A PR to address this issue.  
https://github.com/TheYonkk/influxdb-cpp-2/pull/2
